version: '2'
services:
  server:
    image: ariya/centos6-teamcity-server
    ports:
      - "8111:8111"
    volumes:
      - /data/teamcity
  agent:
    image: ariya/centos6-teamcity-agent
    ports:
      - "9090:9090"
    depends_on:
      - server
    links:
      - server
    environment:
      - TEAMCITY_SERVER=http://server:8111
    tty: true
    volumes:
      - /home/teamcity
    command: sudo -u teamcity -s -- sh -c "echo starting; sleep 40; echo waiting; sleep 40; echo again; sleep 40; TEAMCITY_SERVER=http://server:8111 bash /setup-agent.sh run"
    
    