version: '2'

services:

  server:
    image: ariya/centos6-teamcity-server
    ports:
      - "8111:8111"
    volumes:
    # @TODO switch to volume container
      - /data/teamcity:/data/teamcity

  agent:
    image: local/c7-teamcity-agent
    ports:
      - "9090:9090"
    depends_on:
      - server
    links:
      - server
    environment:
      - TEAMCITY_SERVER=http://server:8111
    tty: true
    volumes:
      - /home/teamcity
      - /var/run/docker.sock:/var/run/docker.sock
      - /bin/docker:/bin/docker
    # oh yes, we need to make a delay while teamcity server starts
    command: sudo -u teamcity -s -- sh -c "echo starting; sleep 35; echo waiting; sleep 35; echo again; sleep 35; TEAMCITY_SERVER=http://server:8111 bash /setup-agent.sh run"

#  dbdata:
#    image: postgres:9.4
#    volumes:
#      - /var/lib/postgresql

#  postgres:
#    image: postgres:9.4
#    volumes_from:
#      - dbdata
#    ports:
#      - "5432"
    
    